services:
  # PostgreSQL 데이터베이스
  db:
    image: postgres:16-alpine
    container_name: naver-crawler-db
    restart: unless-stopped

    environment:
      - POSTGRES_DB=naver_crawler
      - POSTGRES_USER=crawler_user
      - POSTGRES_PASSWORD=crawler_pass_2025
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5434:5432"

    networks:
      - crawler-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crawler_user -d naver_crawler"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Redis 캐시 서버
  redis:
    image: redis:7-alpine
    container_name: naver-crawler-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    networks:
      - crawler-network

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - redis_data:/data

    command: redis-server --appendonly yes

  # Next.js 웹 애플리케이션 (개발 모드)
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: naver-crawler-web
    restart: unless-stopped

    env_file:
      - config.env

    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://crawler_user:crawler_pass_2025@db:5432/naver_crawler?schema=public&connection_limit=20&pool_timeout=30&connect_timeout=10
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development

    # 볼륨 마운트 (개발 모드 - Hot Reload)
    volumes:
      # === 데이터 저장 (NAS) ===
      - ./crawled_data:/app/crawled_data
      - ./logs:/app/logs

      # === 소스 코드 (NAS - Hot Reload용) ===
      - ./app:/app/app
      - ./components:/app/components
      - ./lib:/app/lib
      - ./logic:/app/logic
      - ./hooks:/app/hooks
      - ./prisma:/app/prisma
      - ./public:/app/public
      - ./scripts:/app/scripts
      - ./instrumentation.ts:/app/instrumentation.ts
      - ./next.config.js:/app/next.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./postcss.config.js:/app/postcss.config.js
      - ./dong_code_active.txt:/app/dong_code_active.txt  # 법정동코드 파일

      # === 캐시/빌드 결과 (컨테이너 내부 - 성능 최적화) ===
      - node_modules:/app/node_modules
      - nextjs_cache:/app/.next
      - prisma_cache:/app/node_modules/.prisma

    ports:
      - "3000:3000"

    networks:
      - crawler-network

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

    mem_limit: 4g
    memswap_limit: 4g
    # Chromium은 메모리를 많이 사용 (1.5-2GB)
    # 2GB 제한 시 스왑 발생 → 초기화 120초 (디스크 I/O 병목)

    shm_size: 2gb
    # Chromium 공유 메모리 증설 (기본 64MB는 부족)
    # --disable-dev-shm-usage 옵션과 함께 사용하면 속도 개선

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  crawler-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  node_modules:
  nextjs_cache:
  prisma_cache:
