services:
  # Next.js 웹 애플리케이션
  web:
    build: .
    container_name: naver-crawler-web
    restart: unless-stopped
    
    # 환경변수 파일 사용
    env_file:
      - config.env
    
    # 볼륨 마운트
    volumes:
      - ./crawled_data:/app/crawled_data
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock  # Docker 명령어 실행용
    
    # 포트 설정 (웹 인터페이스)
    ports:
      - "3000:3000"
    
    # 네트워크 설정
    networks:
      - crawler-network
    
    # 리소스 제한 (NAS 호환)
    mem_limit: 2g
    memswap_limit: 2g
    
    # 헬스체크
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  crawler-network:
    driver: bridge

volumes:
  crawled_data:
  logs:
