name: Pull Request Check

on:
  pull_request:
    branches: [main]

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint
      
      - name: Type check
        run: npx tsc --noEmit
      
      - name: Check for console.log
        run: |
          if git diff origin/main...HEAD | grep -E "console\.(log|debug)" | grep -v "console.error\|console.warn"; then
            echo "⚠️  console.log found in changes"
            exit 1
          fi
        continue-on-error: true
      
      - name: PR Summary
        run: |
          echo "✅ All checks passed"
          echo "Files changed: $(git diff --name-only origin/main...HEAD | wc -l)"
          echo "Commits: $(git log origin/main...HEAD --oneline | wc -l)"

